# Generated by Django 5.1.6 on 2025-03-25 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 25)),
        ),
    ]
